export const WS_AUTH_CONNECTION_START = 'WS_AUTH_CONNECTION_START' as const;
export const WS_AUTH_CONNECTION_SUCCESS = 'WS_AUTH_CONNECTION_SUCCESS' as const;
export const WS_AUTH_CONNECTION_ERROR = 'WS_AUTH_CONNECTION_ERROR' as const;
export const WS_AUTH_CONNECTION_CLOSED = 'WS_AUTH_CONNECTION_CLOSED' as const;
export const WS_AUTH_GET_MESSAGE = 'WS_AUTH_GET_MESSAGE' as const;
export const WS_AUTH_SEND_MESSAGE = 'WS_AUTH_SEND_MESSAGE' as const;